nname: CI de Testes Automatizados

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:
  # Executa todos os dias às 12h do Brasil (15h UTC)
  schedule:
    - cron: '0 15 * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  testes-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurando o Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Executando mvn test
        run: mvn test

      - name: Arquivando Relatórios de Teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: |
            target/cucumber-reports.html
            target/cucumber.json
          retention-days: 5

      - name: Enviar Notificação por E-mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Relatório de Testes Playwright: ${{ job.status }}"
          to: ${{ secrets.MAIL_RECIPIENT }}
          from: "GitHub Actions QA"
          body: |
            Olá Glaucio,
            
            Os testes automatizados foram finalizados.
            Status: ${{ job.status }}
            Repositório: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            
            Acesse os detalhes e baixe os artefatos aqui: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}